apiVersion: v2
name: headlamp
description: Headlamp is an easy-to-use and extensible Kubernetes web UI.
icon: https://raw.githubusercontent.com/kubernetes-sigs/headlamp/main/docs/headlamp_light.svg
home: https://headlamp.dev/
type: application
keywords:
  - kubernetes
  - plugins
  - kinvolk
  - headlamp
  - dashboard
  - ui
  - web
  - monitoring
  - logging
sources:
  - https://github.com/kubernetes-sigs/headlamp/tree/main/charts/headlamp
  - https://github.com/kubernetes-sigs/headlamp
version: 0.39.0
appVersion: 0.39.0